import AppKit

/// Polls the general pasteboard's `changeCount` and stores new content in the
/// local clipboard history.
///
/// Polling (rather than `NSPasteboard` notifications) is deliberate: there is no
/// supported notification for pasteboard changes, and a 500 ms poll is what the
/// plan asks for. The poll is cheap — one integer read in the common case.
///
/// Privacy rules applied here:
/// - paused/disabled → nothing is read;
/// - secure keyboard entry active → nothing is read;
/// - content tagged `Transient`/`AutoGenerated` (our own synthetic writes and
///   restores) → ignored, so a paste never re-records itself;
/// - the app the copy came from is in the exclusion list → ignored;
/// - images larger than the policy allows → ignored.
/// As the plan states, the system clipboard cannot label every password copy, so
/// this is best-effort and the settings page says so.
final class ClipboardWatcher {

    private static let log = FileLog("Clipboard.Watch")

    private let store: ClipboardStore
    private var timer: Timer?
    private var lastChangeCount: Int
    private(set) var isRunning = false

    /// Called on the main thread after a new item is stored, so the panel can
    /// refresh if it is open.
    var onChange: (() -> Void)?

    init(store: ClipboardStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard !isRunning else { return }
        isRunning = true
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
        Self.log.info("clipboard watcher started")
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
        Self.log.info("clipboard watcher stopped")
    }

    /// Re-read the baseline (used after a synthetic write we do not want to store).
    func resync() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    deinit { stop() }

    // MARK: - Poll

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        guard ClipboardPreferences.watching else { return }
        guard !FocusedInputInspector.isSecureInputActive() else { return }
        guard !hasTransientMarker(pasteboard) else { return }

        let sourceID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        guard !ClipboardPreferences.isExcluded(bundleID: sourceID) else { return }

        guard let item = makeItem(from: pasteboard, sourceID: sourceID) else { return }
        store.insert(item)
        store.prune(policy: ClipboardPreferences.policy)
        onChange?()
    }

    /// Our own synthetic writes carry the nspasteboard.org transient marker;
    /// compliant restores carry AutoGenerated. Either means "do not record".
    private func hasTransientMarker(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains(Pasteboard.Marker.transient)
            || types.contains(Pasteboard.Marker.autoGenerated)
    }

    private func makeItem(from pasteboard: NSPasteboard, sourceID: String?) -> ClipboardItem? {
        let types = Set(pasteboard.types ?? [])

        // Text and links first: a copied web image often also carries a URL, and
        // the text is the more useful history entry.
        if let string = pasteboard.string(forType: .string),
           !string.isBlankSelection {
            let isURL = types.contains(.URL) || looksLikeURL(string)
            let kind: ClipboardItemKind = isURL ? .url : .text
            let trimmed = string.count > 100_000 ? String(string.prefix(100_000)) : string
            return ClipboardItem(kind: kind, text: trimmed, sourceBundleID: sourceID,
                                 contentHash: ClipboardPolicyEngine.dedupeKey(
                                    kind: kind, text: trimmed, imageDigest: nil))
        }

        // Then images.
        if types.contains(.png) || types.contains(.tiff),
           let png = pngData(from: pasteboard, types: types) {
            let policy = ClipboardPreferences.policy
            guard ClipboardPolicyEngine.shouldStoreImage(byteCount: png.count, policy: policy) else {
                Self.log.info("ignoring image (\(png.count) bytes) — larger than the \(policy.maxImageBytes) byte limit")
                return nil
            }
            let digest = ClipboardStore.digest(png)
            let filename = "\(digest).png"
            let url = store.blobURL(for: filename)
            do {
                try png.write(to: url, options: .atomic)
            } catch {
                Self.log.error("could not write clipboard image: \(error.localizedDescription)")
                return nil
            }
            let preview = imageDescription(from: pasteboard)
            return ClipboardItem(kind: .image, blobPath: filename, preview: preview,
                                 sourceBundleID: sourceID,
                                 contentHash: ClipboardPolicyEngine.dedupeKey(
                                    kind: .image, text: nil, imageDigest: digest))
        }

        return nil
    }

    private func pngData(from pasteboard: NSPasteboard, types: Set<NSPasteboard.PasteboardType>) -> Data? {
        if types.contains(.png), let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func imageDescription(from pasteboard: NSPasteboard) -> String {
        if let tiff = pasteboard.data(forType: .tiff), let rep = NSBitmapImageRep(data: tiff) {
            return "Image \(rep.pixelsWide) × \(rep.pixelsHigh)"
        }
        return "Image"
    }

    private func looksLikeURL(_ text: String) -> Bool {
        guard let url = URL(string: text.trimmingCharacters(in: .whitespacesAndNewlines)),
              let scheme = url.scheme?.lowercased() else { return false }
        return ["http", "https", "ftp", "mailto"].contains(scheme) && url.host != nil
    }
}
