import AppKit

/// Non-destructive pasteboard helpers used by the clipboard-copy fallback.
///
/// Backing up before a synthesized copy and restoring after is what keeps the
/// fallback from clobbering whatever the user already had on their clipboard. We
/// deep-copy *every* item and *every* type (not just the string), matching how
/// the mature reference implementations do it.
///
/// Call these on the main thread (the strategy wraps them in `MainActor.run`).
enum Pasteboard {

    /// nspasteboard.org universal marker types. Well-behaved clipboard managers
    /// honor these and keep the marked write out of their history.
    /// See https://nspasteboard.org
    enum Marker {
        /// "An app placed this with no user Copy intent." Applied to our `restore`
        /// so compliant managers (e.g. Maccy ignores it by default) don't log the
        /// re-placed clipboard as a fresh copy on every PopBar trigger.
        static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        /// Origin of the content, as a bundle id. Per the standard, when restoring
        /// *previous* content whose original source is unknown, set it to the EMPTY
        /// string so a changeCount-scanning manager doesn't misattribute it to us.
        static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")
        /// "This will be gone in a moment." Applied to text we place only so a
        /// synthesized ⌘V can paste it, so managers keep it out of the history.
        static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    }

    /// Snapshot all current pasteboard items (all representations).
    static func backup() -> [NSPasteboardItem] {
        let pasteboard = NSPasteboard.general
        var copied: [NSPasteboardItem] = []
        guard let items = pasteboard.pasteboardItems else { return copied }
        for item in items {
            let dup = NSPasteboardItem()
            // Snapshot the type list first — mutating while iterating `item.types`
            // can crash (a documented edge in the reference code).
            let types = item.types
            for type in types {
                if let data = item.data(forType: type) {
                    dup.setData(data, forType: type)
                }
            }
            copied.append(dup)
        }
        return copied
    }

    /// Restore a previously-captured snapshot. Always clears first so the text we
    /// injected via the synthesized copy is removed — when the snapshot was empty
    /// (the user's clipboard started empty) this correctly leaves it empty again,
    /// rather than leaving our copied selection behind.
    ///
    /// Only call this after a `backup()` + a copy we performed; it unconditionally
    /// overwrites the clipboard.
    @discardableResult
    static func restore(_ items: [NSPasteboardItem]) -> Bool {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard !items.isEmpty else { return true }

        // Tag this restore per nspasteboard.org. It re-places the user's PREVIOUS
        // clipboard — an app-generated write with no user Copy intent (they never
        // ⌘C'd it back). Without a marker, a manager watching `changeCount` records
        // this as a brand-new copy: a spurious duplicate of the user's own clipboard
        // on every PopBar trigger.
        //  - AutoGeneratedType → compliant managers (Maccy ignores it by default)
        //    skip logging it, so no duplicate.
        //  - source = "" (empty) → origin app is unknown to us; the empty string
        //    tells a changeCount-scanning manager NOT to attribute this content to us
        //    (the app that happens to be placing it).
        // The synthesized ⌘C SELECTION itself is written by the FOREGROUND APP, not
        // us, so that write can't be tagged — see ClipboardCopyStrategy.
        for item in items {
            item.setData(Data(), forType: Marker.autoGenerated)
            item.setData(Data(), forType: Marker.source)   // empty string = origin unknown
        }
        return pasteboard.writeObjects(items)
    }
}
